import { useNavigate } from "react-router";
import { withStopPropagation } from "@/utils/utils";
import "@/styles/Frame36128.css";
const Frame36128 = () => {
    const navigate = useNavigate();

    const click_94_1632 = () => {
        navigate(-1);
    };

    const click_94_1635 = () => {
        navigate(-1);
    };

    return (
        <div className="scroll-container">
            <div id="36_128" className="Pixso-frame-36_128">
                <div className="frame-content-36_128">
                    <div id="36_129" className="Pixso-frame-36_129">
                        <div className="frame-content-36_129">
                            <div id="36_131" className="stroke-wrapper-36_131">
                                <div className="Pixso-frame-36_131">
                                    <div className="frame-content-36_131">
                                        <div
                                            id="36_132"
                                            className="Pixso-frame-36_132"
                                        >
                                            <div
                                                id="36_133"
                                                className="Pixso-group-36_133"
                                            >
                                                <div
                                                    id="36_134"
                                                    className="Pixso-rectangle-36_134"
                                                ></div>
                                                <div
                                                    id="36_135"
                                                    className="Pixso-rectangle-36_135"
                                                ></div>
                                                <div
                                                    id="36_136"
                                                    className="Pixso-vector-36_136"
                                                ></div>
                                            </div>
                                            <div
                                                id="36_137"
                                                className="Pixso-group-36_137"
                                            >
                                                <div
                                                    id="36_138"
                                                    className="Pixso-rectangle-36_138"
                                                ></div>
                                            </div>
                                            <div
                                                id="36_139"
                                                className="Pixso-vector-36_139"
                                            ></div>
                                            <div
                                                id="36_143"
                                                className="Pixso-vector-36_143"
                                            ></div>
                                            <div
                                                id="36_145"
                                                className="Pixso-vector-36_145"
                                            ></div>
                                            <div
                                                id="36_147"
                                                className="Pixso-vector-36_147"
                                            ></div>
                                            <div
                                                id="45_19"
                                                className="Pixso-text-45_19"
                                            >
                                                <p
                                                    id="45_19_0"
                                                    className="Pixso-paragraph-45_19_0"
                                                >
                                                    {"&nbsp;"}
                                                </p>
                                            </div>
                                            <p
                                                id="46_1"
                                                className="Pixso-paragraph-46_1"
                                            >
                                                {"Massage Mode"}
                                            </p>
                                            <div
                                                id="46_8"
                                                className="Pixso-vector-46_8"
                                            ></div>
                                            <div
                                                id="46_32"
                                                className="Pixso-vector-46_32"
                                            ></div>
                                            <div
                                                id="46_30"
                                                className="Pixso-vector-46_30"
                                            ></div>
                                            <div
                                                id="46_14"
                                                className="Pixso-vector-46_14"
                                            ></div>
                                            <div
                                                id="46_37"
                                                className="Pixso-vector-46_37"
                                            ></div>
                                        </div>
                                        <p
                                            id="46_13"
                                            className="Pixso-paragraph-46_13"
                                        >
                                            {"Wave"}
                                        </p>
                                        <div
                                            id="36_157"
                                            className="Pixso-frame-36_157"
                                        >
                                            <div
                                                id="36_158"
                                                className="Pixso-frame-36_158"
                                            >
                                                <div
                                                    id="36_159"
                                                    className="Pixso-group-36_159"
                                                >
                                                    <div
                                                        id="36_160"
                                                        className="Pixso-vector-36_160"
                                                    ></div>
                                                    <div
                                                        id="36_161"
                                                        className="Pixso-vector-36_161"
                                                    ></div>
                                                    <div
                                                        id="36_162"
                                                        className="Pixso-vector-36_162"
                                                    ></div>
                                                    <div
                                                        id="36_163"
                                                        className="Pixso-rectangle-36_163"
                                                    ></div>
                                                    <div
                                                        id="36_164"
                                                        className="Pixso-vector-36_164"
                                                    ></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div
                                            id="36_167"
                                            className="Pixso-group-36_167"
                                        >
                                            <div
                                                id="36_172"
                                                className="Pixso-vector-36_172"
                                            ></div>
                                            <div
                                                id="36_173"
                                                className="Pixso-vector-36_173"
                                            ></div>
                                            <div
                                                id="36_174"
                                                className="Pixso-vector-36_174"
                                            ></div>
                                        </div>
                                        <div
                                            id="36_177"
                                            className="Pixso-frame-36_177"
                                        >
                                            <div className="frame-content-36_177">
                                                <p
                                                    id="36_178"
                                                    className="Pixso-paragraph-36_178"
                                                >
                                                    {"Posture"}
                                                </p>
                                                <p
                                                    id="36_179"
                                                    className="Pixso-paragraph-36_179"
                                                >
                                                    {"Heating"}
                                                </p>
                                                <p
                                                    id="36_180"
                                                    className="Pixso-paragraph-36_180"
                                                >
                                                    {"Massage"}
                                                </p>
                                                <p
                                                    id="36_181"
                                                    className="Pixso-paragraph-36_181"
                                                >
                                                    {"Ventilation"}
                                                </p>
                                            </div>
                                        </div>
                                        <div
                                            id="36_186"
                                            className="Pixso-vector-36_186"
                                        ></div>
                                        <p
                                            id="46_19"
                                            className="Pixso-paragraph-46_19"
                                        >
                                            {"Tap"}
                                        </p>
                                        <p
                                            id="46_42"
                                            className="Pixso-paragraph-46_42"
                                        >
                                            {"Waist"}
                                        </p>
                                        <p
                                            id="46_43"
                                            className="Pixso-paragraph-46_43"
                                        >
                                            {"Shoulder"}
                                        </p>
                                        <div
                                            id="46_7"
                                            className="stroke-wrapper-46_7"
                                        >
                                            <div className="Pixso-frame-46_7">
                                                <div className="frame-content-46_7">
                                                    <p
                                                        id="47_1"
                                                        className="Pixso-paragraph-47_1"
                                                    >
                                                        {"Timer"}
                                                    </p>
                                                </div>
                                            </div>
                                            <div className="stroke-46_7"></div>
                                        </div>
                                        <p
                                            id="47_35"
                                            className="Pixso-paragraph-47_35"
                                        >
                                            {"0:45"}
                                        </p>
                                        <div
                                            id="47_32"
                                            className="Pixso-vector-47_32"
                                        ></div>
                                        <div
                                            id="47_22"
                                            className="Pixso-frame-47_22"
                                        ></div>
                                        <p
                                            id="46_6"
                                            className="Pixso-paragraph-46_6"
                                        >
                                            {"Scheduled Time  5min"}
                                        </p>
                                        <div
                                            id="47_23"
                                            className="Pixso-vector-47_23"
                                        ></div>
                                    </div>
                                </div>
                                <div className="stroke-36_131"></div>
                            </div>
                            <div id="36_188" className="stroke-wrapper-36_188">
                                <div className="Pixso-frame-36_188">
                                    <div className="frame-content-36_188">
                                        <div
                                            id="36_189"
                                            className="Pixso-frame-36_189"
                                        >
                                            <div
                                                id="36_190"
                                                className="Pixso-vector-36_190"
                                            ></div>
                                            <div
                                                id="36_192"
                                                className="Pixso-frame-36_192"
                                            >
                                                <div
                                                    id="36_193"
                                                    className="Pixso-frame-36_193"
                                                >
                                                    <p
                                                        id="36_194"
                                                        className="Pixso-paragraph-36_194"
                                                    >
                                                        {"HOME"}
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                        <div
                                            id="36_195"
                                            className="Pixso-frame-36_195"
                                        >
                                            <div
                                                id="36_196"
                                                className="Pixso-frame-36_196"
                                            >
                                                <div
                                                    id="36_197"
                                                    className="Pixso-vector-36_197"
                                                ></div>
                                                <div
                                                    id="36_199"
                                                    className="Pixso-frame-36_199"
                                                ></div>
                                                <p
                                                    id="36_200"
                                                    className="Pixso-paragraph-36_200"
                                                >
                                                    {"MEDIA"}
                                                </p>
                                            </div>
                                        </div>
                                        <div
                                            id="36_201"
                                            className="Pixso-frame-36_201"
                                        >
                                            <div
                                                id="36_202"
                                                className="Pixso-vector-36_202"
                                            ></div>
                                            <div
                                                id="36_204"
                                                className="Pixso-frame-36_204"
                                            >
                                                <div
                                                    id="36_205"
                                                    className="Pixso-frame-36_205"
                                                >
                                                    <p
                                                        id="36_206"
                                                        className="Pixso-paragraph-36_206"
                                                    >
                                                        {"SETTINGS"}
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="stroke-36_188"></div>
                            </div>
                            <div
                                id="96_4"
                                className="Pixso-rectangle-96_4"
                            ></div>
                            <div id="94_1630" className="Pixso-frame-94_1630">
                                <div
                                    id="94_1631"
                                    className="Pixso-rectangle-94_1631"
                                ></div>
                                <div
                                    id="94_1632"
                                    className="Pixso-group-94_1632"
                                    onClick={withStopPropagation(click_94_1632)}
                                >
                                    <div
                                        id="94_1633"
                                        className="Pixso-rectangle-94_1633"
                                    ></div>
                                    <p
                                        id="94_1634"
                                        className="Pixso-paragraph-94_1634"
                                    >
                                        {"Confirm"}
                                    </p>
                                </div>
                                <div
                                    id="94_1635"
                                    className="Pixso-group-94_1635"
                                    onClick={withStopPropagation(click_94_1635)}
                                >
                                    <div
                                        id="94_1636"
                                        className="stroke-wrapper-94_1636"
                                    >
                                        <div className="Pixso-rectangle-94_1636"></div>
                                        <div className="stroke-94_1636"></div>
                                    </div>
                                    <p
                                        id="94_1637"
                                        className="Pixso-paragraph-94_1637"
                                    >
                                        {"Cancel"}
                                    </p>
                                </div>
                                <p
                                    id="94_1638"
                                    className="Pixso-paragraph-94_1638"
                                >
                                    {"Timer"}
                                </p>
                                <div
                                    id="94_1639"
                                    className="Pixso-group-94_1639"
                                >
                                    <div
                                        id="94_1640"
                                        className="Pixso-text-94_1640"
                                    >
                                        <p
                                            id="94_1640_0"
                                            className="Pixso-paragraph-94_1640_0"
                                        >
                                            <span
                                                id="94_1640_0_1"
                                                className="Pixso-span-94_1640_0_1"
                                            >
                                                {"25"}
                                            </span>
                                        </p>
                                        <p
                                            id="94_1640_1"
                                            className="Pixso-paragraph-94_1640_1"
                                        >
                                            <span
                                                id="94_1640_1_1"
                                                className="Pixso-span-94_1640_1_1"
                                            >
                                                {"30"}
                                            </span>
                                        </p>
                                    </div>
                                    <p
                                        id="94_1641"
                                        className="Pixso-paragraph-94_1641"
                                    >
                                        {"05"}
                                    </p>
                                    <div
                                        id="94_1643"
                                        className="Pixso-text-94_1643"
                                    >
                                        <p
                                            id="94_1643_0"
                                            className="Pixso-paragraph-94_1643_0"
                                        >
                                            <span
                                                id="94_1643_0_1"
                                                className="Pixso-span-94_1643_0_1"
                                            >
                                                {"10"}
                                            </span>
                                        </p>
                                        <p
                                            id="94_1643_1"
                                            className="Pixso-paragraph-94_1643_1"
                                        >
                                            <span
                                                id="94_1643_1_1"
                                                className="Pixso-span-94_1643_1_1"
                                            >
                                                {"15"}
                                            </span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};
export default Frame36128;
