export {
  bleManager,
  type DiscoveredDevice,
  type BleConnectionState,
  type BleCallbacks,
} from './ble';

export {
  SERVICE_UUID,
  CHARACTERISTIC_TX,
  CHARACTERISTIC_RX,
  COMPANY_ID,
  HEADER_TX,
  HEADER_RX,
  CMD,
  MOTOR_STOP,
  MOTOR_UP,
  MOTOR_DOWN,
  MASSAGE_MODE,
  HEATING_MODE,
  VENTILATION_MODE,
  LIGHT_MODE,
  AUDIO_MODE,
  POSITION_PRESET,
  VIBRO_MODE,
  LANGUAGE_VAL,
  calcChecksum,
  buildFrame,
  bytesToHex,
  parseFrame,
  type ParsedFrame,
  buildMotorCmd,
  buildPositionCmd,
  buildMemoryRunCmd,
  buildMemorySetCmd,
  buildMassageCmd,
  buildMassageIntensityCmd,
  buildHeatingCmd,
  buildHeatingModeCmd,
  buildVentilationCmd,
  buildVentilationModeCmd,
  buildTimerCmd,
  buildLightCmd,
  buildLightColorCmd,
  buildVibroCmd,
  buildVibroIntensityCmd,
  buildAudioModeCmd,
  buildAudioTrebleCmd,
  buildAudioBassCmd,
  buildAudioVolumeCmd,
  buildChildLockCmd,
  buildVersionCmd,
} from './protocol';

export {
  parseAdvertisingData,
  extractManufacturerData,
  parseStatusReport,
  massageModeFromProtocol,
  massageModeToProtocol,
  heatingModeToProtocol,
  ventilationModeToProtocol,
  audioModeToProtocol,
  vibroModeToProtocol,
  lightModeToProtocol,
  type MotorConfig,
  type MotorKind,
  type MotorType,
  type DeviceConfig,
  type HeatingConfig,
  type VentilationConfig,
  type HeatingZoneKey,
  type VentilationZoneKey,
  HEATING_ZONE_ORDER,
  VENTILATION_ZONE_ORDER,
  type MassageConfig,
  type MassageSystem,
  type MultimediaConfig,
  type FullDeviceState,
  type MotorState,
  type MassageState,
  type HeatingZoneState,
  type VentilationZoneState,
  type LightState,
  type WaistState,
  type VibroState,
  type AudioState,
  type PairingState,
} from './parser';
